services:
  mongodb:
    image: mongo:8.0
    container_name: zlschat-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: zlschat
    volumes:
      - zlschat-volume:/data/db
    restart: always
    networks:
      - zlschat-network

  api:
    build:
      context: .
    container_name: zlschat-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    restart: always
    environment:
      SERVER_PORT: 8080
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: zlschat
      MONGODB_AUTHENTICATION_DATABASE: admin
      MONGODB_AUTO_INDEX_CREATION: true
      JWT_SECRET: 1311f8fc80a7ea28d78dd7723f09c44c1754cd35160ca8e7133ae3d7f636a19a
      CORS_ORIGIN: http://localhost:3000
    networks:
      - zlschat-network

volumes:
  zlschat-volume:
    name: zlschat-volume
    driver: local

networks:
  zlschat-network:
    name: zlschat-app
    driver: bridge