services:
  mongodb:
    image: mongo:8.0
    container_name: zlschat-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: zlschat
    volumes:
      - zlschat-volume:/var/lib/mongo/data
    networks:
      - zlschat-network

  rabbitmq:
    image: rabbitmq:3.12.5-management-alpine
    container_name: zlschat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - zlschat-network

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: zlschat-redis
    ports:
      - "6379:6379"
    networks:
      - zlschat-network

  # api:
  #   build:
  #     context: .
  #   container_name: zlschat-api
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongodb
  #   restart: always
  #   environment:
  #     SERVER_PORT: 8080
  #     MONGODB_URI: mongodb://admin:password@localhost:27017/zlschat?authSource=admin
  #     RABBITMQ_URI: amqp://user:password@localhost:5672
  #     JWT_SECRET: 1311f8fc80a7ea28d78dd7723f09c44c1754cd35160ca8e7133ae3d7f636a19a
  #     CORS_ORIGIN: http://localhost:3000
  #   networks:
  #     - zlschat-network

volumes:
  zlschat-volume:

networks:
  zlschat-network:
    driver: bridge