services:
  mongodb:
    image: mongo:8.0
    container_name: websocket-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=websocket
    volumes:
      - zlschat-volume:/data/db
    restart: always

volumes:
  zlschat-volume:
    driver: local