name: ZlsChat API | Deploy to AWS App Runner

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: AWS_CREDENTIALS
        permissions:
            id-token: write
            contents: read

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                role-to-assume: "${{ secrets.ECR_ARN_ROLE }}"
                aws-region: us-east-1

          - name: Deploy to AWS App Runner
            id: deploy-apprunner
            uses: awslabs/amazon-app-runner-deploy@main
            with:
                service: zlschat-api
                access-role-arn: "${{ secrets.APP_RUNNER_ARN_ROLE }}"
                region: us-east-1
                cpu: 1
                memory: 2
                port: 8080
                image: 